# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b376e3804593ceaaa98bec3ade1ba5aabecc695b33dc586f94d8a16c631c95f36701cafa14f04b97384725ec588f3b379112f632cda564c41cd055022feee4ca

test:
  secret_key_base: 905d12eb2af6902313108cc4a1c056ec48edcb3dc0489b774a6b79bef66a33951c1fe515b9f8047c70c89f1e78e701ad16b3c3bd781d7c78ae1cf087ebc6e054

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
